name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true

  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What type of bug is this?
      options:
        - Link not working
        - Auto-completion issues
        - Performance problems
        - Configuration not working
        - Visual/UI issues
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide your environment details
      placeholder: |
        - OS: [e.g. macOS 14.0, Windows 11, Ubuntu 22.04]
        - Cursor IDE Version: [e.g. 0.42.0]
        - Extension Version: [e.g. 0.1.4]
        - File Types: [e.g. .ts, .js, .md]
    validations:
      required: true

  - type: textarea
    id: configuration
    attributes:
      label: Configuration
      description: Your MDC Link extension configuration (if relevant)
      placeholder: |
        ```json
        {
          "mdcLink.enableForAllFiles": true,
          "mdcLink.allowedExtensions": [".ts", ".js", ".md"],
          "mdcLink.validateLinks": true
        }
        ```

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: If applicable, provide example code that demonstrates the issue
      placeholder: |
        ```typescript
        // Example MDC link that's not working
        [UserService](mdc:user-service.ts)
        ```

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: Any relevant console logs or error messages
      placeholder: |
        Open Developer Tools (Ctrl+Shift+P → "Developer: Toggle Developer Tools") and check the Console tab for any MDC Link Extension messages.

  - type: checkboxes
    id: troubleshooting
    attributes:
      label: Troubleshooting
      description: Please check the following before submitting
      options:
        - label: I have checked that the extension is enabled
        - label: I have verified the target file exists
        - label: I have checked the file extension is in allowedExtensions
        - label: I have tried restarting Cursor IDE
        - label: I have checked the Developer Console for errors

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...
